trigger:
- "*"

variables:
  rp: go/src/github.com/actions/migrate
  wd: $(Pipeline.Workspace)/$(rp)
  GOPATH: $(Pipeline.Workspace)/go

strategy:
  matrix:
    windows:
      os: vs2017-win2016
    linux:
      os: 'ubuntu-16.04'
    osx:
      os: macOS-10.13

pool:
  vmImage: $(os)

steps:
- checkout: self
  path: $(rp)
- task: GoTool@0
  inputs:
    version: '1.12'
    workingDirectory: $(wd)
- bash: ./script/check-format
  displayName: Check format
  continueOnError: true
  workingDirectory: $(wd)
- bash: ./script/build
  displayName: Build
  workingDirectory: $(wd)
- bash: ls -l "$(wd)/bin"
  displayName: See what is built
- bash: ./script/test
  displayName: Test
  workingDirectory: $(wd)
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true
- bash: ruby ./script/functional-test.rb
  workingDirectory: $(wd)
  displayName: "Functional test of binary"
